[package]
name = "Matt-Magie"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
regex = "1.11.1"
rand = "0.8.5"